"""make usage_log session_id nullable

Revision ID: 19415a5fd1d8
Revises: 
Create Date: 2026-04-02 14:00:13.802728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19415a5fd1d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
